[phases.setup]
nixPkgs = ["python310", "nodejs_18"]

[phases.build]
cmds = [
    "cd rental-site && npm install --legacy-peer-deps",
    "cd rental-site && VITE_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY npm run build",
    "mkdir -p backend/src/static",
    "rm -rf backend/src/static/*",
    "cp -r rental-site/dist/* backend/src/static/"
]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level debug --access-logfile - --error-logfile - wsgi:app"

