services:
  - type: web
    name: the-wild-share
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app
    envVars:
      - key: FLASK_APP
        value: src/main.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
